app <- ShinyDriver$new("../../")
app$snapshotInit("test_99_settings_pi")

app$setInputs(menu = "settings")
app$setInputs(opts_b = 100)
app$setInputs(menu = "data")
app$uploadFile(survey_file = "../../../extdata/UKH2017_MMU_Querried_data_for_Analysis_Final_3.csv")
app$setInputs(sidebarItemExpanded = "Total")
app$setInputs(menu = "total_models")
app$setInputs(total_model_dist = "P")
app$setInputs(total_model_var_count = "AllNeedleWet")
app$setInputs(total_model_add = "click")
app$setInputs(menu = "total_pi")
app$setInputs(total_pi_models = "A")
app$setInputs(total_pi_calc = "click")
app$snapshot()

app$setInputs(menu = "settings")
app$setInputs(opts_b = 500)
app$snapshot()

app$setInputs(menu = "total_pi")
app$snapshot()

app$setInputs(total_pi_models = "A")
app$setInputs(total_pi_calc = "click", timeout_ = 5000)
app$snapshot()
