app <- ShinyDriver$new("../../")
app$snapshotInit("test_01_data_filters")

app$setInputs(menu = "data")
app$uploadFile(survey_file = "../../../extdata/UKH2017_MMU_Querried_data_for_Analysis_Final_3.csv")
app$setInputs(data_panel = "Data Structure")
app$setInputs(survey_omit = character(0))
app$snapshot()
app$setInputs(survey_omit = "GMS")
app$snapshot()
app$setInputs(survey_factors = c("MMU_ID", "LKStrat_01"))
app$snapshot()
app$setInputs(filter_SURVEY_NAM = "Upper Klondike Hwy MMU")
app$snapshot()
app$setInputs(filter_SURVEY_YEA = "2017")
app$snapshot()
