app <- ShinyDriver$new("../../")
app$snapshotInit("test_99_settings_models")

app$setInputs(menu = "data")
app$uploadFile(survey_file = "../../../extdata/UKH_2017_QuerriedSU_Final_Corrected_for_Analysis.csv")
app$setInputs(sidebarItemExpanded = "Total")
app$setInputs(menu = "addmodel")
app$setInputs(model_var_count = c("NALC_AllNeedleWet", "Fire8212_DEM815_Sub"))
app$setInputs(model_var_zero = c("NALC_AllNeedleWet", "DShMiFires815_Sub"))
app$setInputs(model_add = "click")
app$setInputs(model_dist = "NB")
app$setInputs(model_add = "click")
app$setInputs(model_weighted = "TRUE")
app$setInputs(model_dist = "ZIP")
app$setInputs(model_add = "click")
app$setInputs(model_dist = "ZINB")
app$setInputs(model_add = "click")
app$snapshot()

# Change and test settings
app$setInputs(menu = "settings")
app$setInputs(opts_response = "cows")
app$setInputs(opts_sightability = 0.1, timeout_ = 5000)
app$setInputs(opts_alpha = "0.1", timeout_ = 5000)
app$setInputs(opts_method = "BFGS")
app$snapshot()
app$setInputs(menu = "addmodel")
app$snapshot()

app$setInputs(menu = "settings")
app$setInputs(opts_method = "CG")
app$setInputs(menu = "addmodel")
app$snapshot()

app$setInputs(menu = "settings")
app$setInputs(opts_method = "L-BFGS-B")
app$setInputs(menu = "addmodel")
app$snapshot()

app$setInputs(menu = "settings")
app$setInputs(opts_method = "SANN", timeout_ = 5000)
app$setInputs(menu = "addmodel")
app$snapshot()

