on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: check

jobs:
  deploy:
    runs-on: macOS-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: R setup
        uses: r-lib/actions/setup-r@v2

      - name: Install pandoc
        run: |
          brew install pandoc
          brew install --cask xquartz

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("pkgdown", "devtools"))'
          Rscript -e 'devtools::install_dev_deps()'

      - name: Check package
        run: Rscript -e 'devtools::check()'

      - name: Build site
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: Rscript -e 'pkgdown::build_site_github_pages(install=TRUE)'

      - name: Deploy site
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
          clean: true
